### PR TITLE
Added check and move for temp image files in application directory

### PR DESCRIPTION
**Pull request by xhp-creations**
Added check and move for temp image files in application directory, instead of TexConv directory.

Added option for deleting temp image files on exit.

### CODE REVIEW

**Comment by xhp-creations** [comment]
Sorry, accidentally changed the compile to AnyCPU from x64, but I will be fixing that real quick and can either submit that as another pull request after you accept this one, or you can easily fix it yourself, but other than that, this commit should be acceptable I hope.

**Comment by xhp-creations** [comment]
Nevermind, it added the second commit of me fixing that.  HAHA

**Comment by pozzum** [comment]
Merging, nice to see you BrienJ I will edit the on close function to call the `DeleteCurrentImage` command (and probably rename it to DeleteTempImages) and modify that command accordingly with your updates.  It's supposed to delete the temp files on exit of the picture tab so I will also change the default of deletetempbmp setting to true.  Thanks for the contribution!

**Comment by xhp-creations** [comment]
No problem.  I want to help with anything I can.

**Pull request merged**
